// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDEVD71sC6fyHrNo-PUFAvncK0O_YubxI',
    appId: '1:280495227409:web:b883970ee11678aa3127b0',
    messagingSenderId: '280495227409',
    projectId: 'pizzariapp-90c96',
    authDomain: 'pizzariapp-90c96.firebaseapp.com',
    storageBucket: 'pizzariapp-90c96.firebasestorage.app',
    measurementId: 'G-7VBCKN9C9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM-sKGR-R8Q2hHvq2o4LFmTkQkHS_jTAo',
    appId: '1:280495227409:android:758f10ede301b5c53127b0',
    messagingSenderId: '280495227409',
    projectId: 'pizzariapp-90c96',
    storageBucket: 'pizzariapp-90c96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8nLg0l7WOdHYvv_32GUbjt7IUU76_C44',
    appId: '1:280495227409:ios:e6518b741f38c2e83127b0',
    messagingSenderId: '280495227409',
    projectId: 'pizzariapp-90c96',
    storageBucket: 'pizzariapp-90c96.firebasestorage.app',
    iosBundleId: 'com.example.pizzariaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8nLg0l7WOdHYvv_32GUbjt7IUU76_C44',
    appId: '1:280495227409:ios:e6518b741f38c2e83127b0',
    messagingSenderId: '280495227409',
    projectId: 'pizzariapp-90c96',
    storageBucket: 'pizzariapp-90c96.firebasestorage.app',
    iosBundleId: 'com.example.pizzariaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDEVD71sC6fyHrNo-PUFAvncK0O_YubxI',
    appId: '1:280495227409:web:3b8c52a516a216313127b0',
    messagingSenderId: '280495227409',
    projectId: 'pizzariapp-90c96',
    authDomain: 'pizzariapp-90c96.firebaseapp.com',
    storageBucket: 'pizzariapp-90c96.firebasestorage.app',
    measurementId: 'G-1TZY1WQ1XP',
  );
}
